In [1]:
import numpy as np
import teneva
from time import perf_counter as tpc
np.random.seed(42)

In [2]:
d    = 5                          # Dimension of the function
a    = [-5., -4., -3., -2., -1.]  # Lower bounds for spatial grid
b    = [+6., +3., +3., +1., +2.]  # Upper bounds for spatial grid
n    = [ 10,  12,  14,  16,  18]  # Shape of the tensor

In [3]:
m    = 1.E+4                      # Number of calls to target function
nswp = 50                         # Sweep number for ALS iterations
r    = 5                          # TT-rank of the initial random tensor

In [4]:
def func(I):
    """Schaffer function."""
    X = teneva.ind_to_poi(I, a, b, n)
    Z = X[:, :-1]**2 + X[:, 1:]**2
    y = 0.5 + (np.sin(np.sqrt(Z))**2 - 0.5) / (1. + 0.001 * Z)**2
    return np.sum(y, axis=1)

In [5]:
I_trn = teneva.sample_lhs(n, m, seed=42) 
y_trn = func(I_trn)

In [6]:
I_vld = teneva.sample_rand(n, 1.E+3, seed=99) 
y_vld = func(I_vld)

In [7]:
I_tst = teneva.sample_rand(n, 1.E+4, seed=42) 
y_tst = func(I_tst)

In [8]:
t = tpc()
Y = teneva.anova(I_trn, y_trn, r)
Y = teneva.als(I_trn, y_trn, Y, nswp)
t = tpc() - t

print(f'Build time     : {t:-10.2f}')

Build time     :       1.71


In [9]:
print(f'Error on train : {teneva.accuracy_on_data(Y, I_trn, y_trn):-10.2e}')
print(f'Error on valid.: {teneva.accuracy_on_data(Y, I_vld, y_vld):-10.2e}')
print(f'Error on test  : {teneva.accuracy_on_data(Y, I_tst, y_tst):-10.2e}')

Error on train :   1.28e-03
Error on valid.:   1.45e-03
Error on test  :   1.45e-03


In [22]:
k = 0
i = I_trn[k]
y = y_trn[k]

Y = teneva.rand(n, r)
Y = teneva.als(i.reshape(1, -1), [y], Y, e=1.E-12, I_vld=I_vld[k].reshape(1, -1), y_vld=[y_vld[k]], log=True, 
    update_sol=True, lamb=10000000, allow_skip_cores=True)

# pre | time:      0.000 | rank:   5.0 | e_vld: 8.4e-01 | 
#   1 | time:      0.006 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   2 | time:      0.011 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   3 | time:      0.017 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   4 | time:      0.021 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   5 | time:      0.025 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   6 | time:      0.029 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   7 | time:      0.033 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   8 | time:      0.037 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#   9 | time:      0.040 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#  10 | time:      0.043 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#  11 | time:      0.046 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#  12 | time:      0.050 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#  13 | time:      0.054 | rank:   5.0 | e_vld: 8.4e-01 | e: 6.5e-09 | 
#  14

In [30]:
from copy import deepcopy as copy
copy(42)

42

In [31]:
x = [1, 1, 2, 1, 4, 3, 2, 6]
np.maximum.accumulate(x)

array([1, 1, 2, 2, 4, 4, 4, 6])

In [32]:
np.minimum.accumulate(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [34]:
dx = np.array([0.6, 0.7, 0., -0.4])
np.where(np.abs(dx) > 1.E-16)[0]

array([0, 1, 3])

array([[-2.  ,  0.  ,  2.  ],
       [ 2.  ,  0.  ,  1.25]])